Add missing <array> include
smb/transfer.h:70:62: error: implicit instantiation of undefined template 'std::__1::array<std::__1::unique_ptr<TransferSegment, std::__1::default_delete<TransferSegment> >, 4>'
    std::array<std::unique_ptr<TransferSegment>, m_capacity> m_buffer;
                                                             ^
/usr/include/c++/v1/__tuple:219:64: note: template is declared here
template <class _Tp, size_t _Size> struct _LIBCPP_TEMPLATE_VIS array;
                                                               ^
1 error generated.