sftp: Fix build failure with old libssh versions
Building kio-sftp fails on Ubuntu 18.04:
kio-extras/sftp/kio_sftp.cpp:1280:1: error: non-void function does not return a value in all control paths [-Werror,-Wreturn-type]
}
^
1 error generated.
make[2]: *** [sftp/CMakeFiles/kio_sftp.dir/kio_sftp.cpp.o] Error 1
make[1]: *** [sftp/CMakeFiles/kio_sftp.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [all] Error 2

SFTPInternal::openConnection() version for libssh < 0.8.3 is missing a
return at the end of the function. Add it.